In [2]:
import numpy as np
import pandas as pd

In [3]:
pitch_stats = pd.read_csv("https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Pitching.csv",sep=',')

In [4]:
pitch_stats

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
0,bechtge01,1871,1,PH1,NaN,1,2,3,3,2,...,NaN,7,NaN,0,146.0,0,42,NaN,NaN,NaN
1,brainas01,1871,1,WS3,NaN,12,15,30,30,30,...,NaN,7,NaN,0,1291.0,0,292,NaN,NaN,NaN
2,fergubo01,1871,1,NY2,NaN,0,0,1,0,0,...,NaN,2,NaN,0,14.0,0,9,NaN,NaN,NaN
3,fishech01,1871,1,RC1,NaN,4,16,24,24,22,...,NaN,20,NaN,0,1080.0,1,257,NaN,NaN,NaN
4,fleetfr01,1871,1,NY2,NaN,0,1,1,1,1,...,NaN,0,NaN,0,57.0,0,21,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48394,zeuchtj01,2020,1,TOR,AL,1,0,3,1,0,...,0.0,0,0.0,0,47.0,1,2,0.0,0.0,0.0
48395,zimmebr02,2020,1,BAL,AL,0,0,2,1,0,...,0.0,2,2.0,0,31.0,1,6,0.0,0.0,1.0
48396,zimmejo02,2020,1,DET,AL,0,0,3,2,0,...,0.0,0,0.0,0,28.0,0,6,0.0,0.0,1.0
48397,zimmeky01,2020,1,KCA,AL,1,0,16,1,0,...,0.0,2,1.0,0,91.0,4,4,0.0,0.0,3.0
48398,zuberty01,2020,1,KCA,AL,1,2,23,0,0,...,1.0,1,1.0,0,99.0,8,11,1.0,1.0,3.0